import type { User, Community, Post, Comment, Notification, Conversation, Message, Report, Ban } from '../types';

// ─── Users ──────────────────────────────────────────────────────────────────
export const mockUsers: User[] = [
  {
    id: 'u1',
    username: 'alexchen',
    displayName: 'Alex Chen',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alex',
    banner: 'https://picsum.photos/seed/banner1/800/200',
    bio: 'Full-stack developer. Open source enthusiast. Coffee addict.',
    karma: 48520,
    followersCount: 1240,
    followingCount: 356,
    joinedAt: '2022-03-15T10:00:00Z',
    isOnline: true,
    isVerified: true,
    role: 'admin',
  },
  {
    id: 'u2',
    username: 'sarahmiller',
    displayName: 'Sarah Miller',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarah',
    banner: 'https://picsum.photos/seed/banner2/800/200',
    bio: 'Photographer & visual storyteller. Based in Portland.',
    karma: 32100,
    followersCount: 890,
    followingCount: 445,
    joinedAt: '2021-08-22T10:00:00Z',
    isOnline: true,
    isVerified: false,
    role: 'moderator',
  },
  {
    id: 'u3',
    username: 'jordanlee',
    displayName: 'Jordan Lee',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jordan',
    bio: 'Gamer, streamer, and tech reviewer.',
    karma: 27800,
    followersCount: 2100,
    followingCount: 180,
    joinedAt: '2023-01-10T10:00:00Z',
    isOnline: false,
    isVerified: false,
    role: 'user',
  },
  {
    id: 'u4',
    username: 'emilyzhang',
    displayName: 'Emily Zhang',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=emily',
    bio: 'Data scientist by day, artist by night.',
    karma: 19500,
    followersCount: 670,
    followingCount: 290,
    joinedAt: '2022-11-05T10:00:00Z',
    isOnline: true,
    isVerified: false,
    role: 'user',
  },
  {
    id: 'u5',
    username: 'marcusjohnson',
    displayName: 'Marcus Johnson',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=marcus',
    bio: 'Music producer and audio engineer.',
    karma: 15200,
    followersCount: 430,
    followingCount: 510,
    joinedAt: '2023-04-18T10:00:00Z',
    isOnline: false,
    isVerified: false,
    role: 'user',
  },
  {
    id: 'u6',
    username: 'oliviawong',
    displayName: 'Olivia Wong',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=olivia',
    bio: 'UX designer passionate about accessibility.',
    karma: 22300,
    followersCount: 780,
    followingCount: 320,
    joinedAt: '2022-06-30T10:00:00Z',
    isOnline: true,
    isVerified: true,
    role: 'moderator',
  },
  {
    id: 'u7',
    username: 'davidkim',
    displayName: 'David Kim',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=david',
    bio: 'Startup founder. Building the future of work.',
    karma: 41000,
    followersCount: 3200,
    followingCount: 150,
    joinedAt: '2021-02-14T10:00:00Z',
    isOnline: false,
    isVerified: true,
    role: 'user',
  },
  {
    id: 'u8',
    username: 'lisapark',
    displayName: 'Lisa Park',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=lisa',
    bio: 'Travel blogger. 45 countries and counting.',
    karma: 36700,
    followersCount: 1500,
    followingCount: 890,
    joinedAt: '2021-09-20T10:00:00Z',
    isOnline: true,
    isVerified: false,
    role: 'user',
  },
];

// ─── Communities ────────────────────────────────────────────────────────────
export const mockCommunities: Community[] = [
  {
    id: 'c1',
    slug: 'technology',
    name: 'Technology',
    description: 'The latest in tech news, gadgets, and innovation. Discuss everything from AI to quantum computing.',
    icon: 'https://api.dicebear.com/7.x/shapes/svg?seed=tech',
    banner: 'https://picsum.photos/seed/techbanner/1200/300',
    membersCount: 2450000,
    onlineCount: 12400,
    createdAt: '2020-01-15T10:00:00Z',
    category: 'Technology',
    rules: [
      { id: 'r1', title: 'Be respectful', description: 'Treat others with respect. No personal attacks or harassment.' },
      { id: 'r2', title: 'No spam', description: 'Do not post spam or self-promotional content without contributing to the community.' },
      { id: 'r3', title: 'Stay on topic', description: 'Posts must be related to technology.' },
      { id: 'r4', title: 'No misinformation', description: 'Back up claims with sources when possible.' },
    ],
    moderators: ['u1', 'u2'],
    isJoined: true,
    isFollowing: true,
  },
  {
    id: 'c2',
    slug: 'gaming',
    name: 'Gaming',
    description: 'Your destination for all things gaming. PC, console, mobile, and everything in between.',
    icon: 'https://api.dicebear.com/7.x/shapes/svg?seed=gaming',
    banner: 'https://picsum.photos/seed/gamingbanner/1200/300',
    membersCount: 3200000,
    onlineCount: 18500,
    createdAt: '2020-01-20T10:00:00Z',
    category: 'Gaming',
    rules: [
      { id: 'r1', title: 'No spoilers', description: 'Use spoiler tags for recent game releases.' },
      { id: 'r2', title: 'Be respectful', description: 'No toxicity or harassment.' },
    ],
    moderators: ['u3'],
    isJoined: true,
    isFollowing: false,
  },
  {
    id: 'c3',
    slug: 'photography',
    name: 'Photography',
    description: 'Share your photos, get feedback, and discuss techniques. All skill levels welcome.',
    icon: 'https://api.dicebear.com/7.x/shapes/svg?seed=photo',
    banner: 'https://picsum.photos/seed/photobanner/1200/300',
    membersCount: 1800000,
    onlineCount: 8900,
    createdAt: '2020-02-10T10:00:00Z',
    category: 'Arts',
    rules: [
      { id: 'r1', title: 'Share your work', description: 'Post your own photos for feedback.' },
      { id: 'r2', title: 'Constructive criticism', description: 'Give helpful, constructive feedback.' },
    ],
    moderators: ['u2', 'u6'],
    isJoined: false,
    isFollowing: true,
  },
  {
    id: 'c4',
    slug: 'science',
    name: 'Science',
    description: 'Explore the wonders of science. Physics, biology, chemistry, astronomy, and more.',
    icon: 'https://api.dicebear.com/7.x/shapes/svg?seed=science',
    banner: 'https://picsum.photos/seed/sciencebanner/1200/300',
    membersCount: 1500000,
    onlineCount: 6700,
    createdAt: '2020-03-05T10:00:00Z',
    category: 'Science',
    rules: [
      { id: 'r1', title: 'Cite sources', description: 'Always cite peer-reviewed sources.' },
      { id: 'r2', title: 'No pseudoscience', description: 'No flat earth, anti-vax, or other pseudoscience.' },
    ],
    moderators: ['u4'],
    isJoined: false,
    isFollowing: false,
  },
  {
    id: 'c5',
    slug: 'music',
    name: 'Music',
    description: 'Discover new music, share your playlists, and discuss your favorite artists.',
    icon: 'https://api.dicebear.com/7.x/shapes/svg?seed=music',
    banner: 'https://picsum.photos/seed/musicbanner/1200/300',
    membersCount: 2100000,
    onlineCount: 11200,
    createdAt: '2020-01-25T10:00:00Z',
    category: 'Entertainment',
    rules: [
      { id: 'r1', title: 'Share music', description: 'Post links to music you love.' },
      { id: 'r2', title: 'Respect artists', description: 'No piracy links.' },
    ],
    moderators: ['u5'],
    isJoined: true,
    isFollowing: true,
  },
  {
    id: 'c6',
    slug: 'design',
    name: 'Design',
    description: 'UI/UX, graphic design, product design, and visual arts. Share your work and get feedback.',
    icon: 'https://api.dicebear.com/7.x/shapes/svg?seed=design',
    banner: 'https://picsum.photos/seed/designbanner/1200/300',
    membersCount: 980000,
    onlineCount: 4500,
    createdAt: '2020-04-12T10:00:00Z',
    category: 'Arts',
    rules: [
      { id: 'r1', title: 'Share your work', description: 'Post your designs for feedback.' },
      { id: 'r2', title: 'Be constructive', description: 'Give helpful feedback.' },
    ],
    moderators: ['u6'],
    isJoined: false,
    isFollowing: false,
  },
  {
    id: 'c7',
    slug: 'movies',
    name: 'Movies',
    description: 'Discuss the latest films, classics, and everything cinema.',
    icon: 'https://api.dicebear.com/7.x/shapes/svg?seed=movies',
    banner: 'https://picsum.photos/seed/moviebanner/1200/300',
    membersCount: 1750000,
    onlineCount: 7800,
    createdAt: '2020-02-28T10:00:00Z',
    category: 'Entertainment',
    rules: [
      { id: 'r1', title: 'Use spoiler tags', description: 'Tag spoilers for recent releases.' },
    ],
    moderators: ['u8'],
    isJoined: false,
    isFollowing: true,
  },
  {
    id: 'c8',
    slug: 'programming',
    name: 'Programming',
    description: 'Code, algorithms, software engineering, and computer science.',
    icon: 'https://api.dicebear.com/7.x/shapes/svg?seed=code',
    banner: 'https://picsum.photos/seed/codebanner/1200/300',
    membersCount: 2800000,
    onlineCount: 15600,
    createdAt: '2020-01-18T10:00:00Z',
    category: 'Technology',
    rules: [
      { id: 'r1', title: 'No homework help', description: 'No "do my homework" posts.' },
      { id: 'r2', title: 'Use code blocks', description: 'Format code properly.' },
    ],
    moderators: ['u1', 'u7'],
    isJoined: true,
    isFollowing: true,
  },
];

// ─── Posts ──────────────────────────────────────────────────────────────────
export const mockPosts: Post[] = [
  {
    id: 'p1',
    communityId: 'c1',
    communityName: 'Technology',
    communitySlug: 'technology',
    communityIcon: 'https://api.dicebear.com/7.x/shapes/svg?seed=tech',
    authorId: 'u1',
    authorName: 'alexchen',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alex',
    authorRole: 'admin',
    title: 'Apple announces M4 chip with revolutionary AI capabilities',
    body: 'Apple just unveiled their new M4 chip at the October event. The new chip features a 16-core Neural Engine capable of 38 trillion operations per second, specifically designed for AI workloads. Early benchmarks show a 40% improvement in machine learning tasks compared to the M3.\n\nThe chip will first appear in the new MacBook Pro lineup, with iPad Pro and Mac mini getting it early next year. What are your thoughts on Apple\'s AI strategy?',
    type: 'text',
    media: [],
    flair: 'News',
    flairColor: 'blue',
    score: 1842,
    userVote: 1,
    commentsCount: 342,
    repostsCount: 128,
    isReposted: false,
    createdAt: '2026-09-29T08:30:00Z',
    isSaved: false,
    isHidden: false,
    isSpoiler: false,
    isNSFW: false,
    isPinned: false,
    isLocked: false,
  },
  {
    id: 'p2',
    communityId: 'c2',
    communityName: 'Gaming',
    communitySlug: 'gaming',
    communityIcon: 'https://api.dicebear.com/7.x/shapes/svg?seed=gaming',
    authorId: 'u3',
    authorName: 'jordanlee',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jordan',
    title: 'Elden Ring Nightreign - First Impressions after 20 hours',
    body: 'Just finished my 20-hour playthrough of Elden Ring Nightreign and I have thoughts.\n\nThe combat is as tight as ever, but the new roguelike elements add a fresh layer of strategy. The boss designs are incredible - some of the best FromSoftware has ever created.\n\nHowever, the performance on PC needs work. I\'m getting frame drops in certain areas that really break immersion.',
    type: 'text',
    media: [
      {
        id: 'm1',
        type: 'image',
        url: 'https://picsum.photos/seed/eldenring/800/450',
        width: 800,
        height: 450,
      },
    ],
    flair: 'Review',
    flairColor: 'green',
    score: 892,
    userVote: 0,
    commentsCount: 156,
    repostsCount: 45,
    isReposted: false,
    createdAt: '2026-09-29T06:15:00Z',
    isSaved: true,
    isHidden: false,
    isSpoiler: false,
    isNSFW: false,
    isPinned: false,
    isLocked: false,
  },
  {
    id: 'p3',
    communityId: 'c3',
    communityName: 'Photography',
    communitySlug: 'photography',
    communityIcon: 'https://api.dicebear.com/7.x/shapes/svg?seed=photo',
    authorId: 'u2',
    authorName: 'sarahmiller',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarah',
    authorRole: 'moderator',
    title: 'Golden hour at the Oregon coast - shot on Fuji X-T5',
    body: 'Spent the weekend at Cannon Beach and caught the most incredible golden hour light. Shot on the Fuji X-T5 with the 23mm f/1.4 lens.\n\nSettings: ISO 160, f/8, 1/250s\n\nWould love to hear your thoughts on the composition!',
    type: 'image',
    media: [
      {
        id: 'm2',
        type: 'image',
        url: 'https://picsum.photos/seed/oregoncoast/1200/800',
        width: 1200,
        height: 800,
      },
    ],
    flair: 'OC',
    flairColor: 'purple',
    score: 2341,
    userVote: 1,
    commentsCount: 89,
    repostsCount: 234,
    isReposted: false,
    createdAt: '2026-09-28T22:45:00Z',
    isSaved: false,
    isHidden: false,
    isSpoiler: false,
    isNSFW: false,
    isPinned: false,
    isLocked: false,
  },
  {
    id: 'p4',
    communityId: 'c8',
    communityName: 'Programming',
    communitySlug: 'programming',
    communityIcon: 'https://api.dicebear.com/7.x/shapes/svg?seed=code',
    authorId: 'u7',
    authorName: 'davidkim',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=david',
    title: 'Why I switched from microservices back to a monolith (and why you might too)',
    body: 'After 3 years of running a microservices architecture at scale, we made the controversial decision to consolidate back into a modular monolith. Here\'s why:\n\n1. **Operational complexity** - We had 47 services, each with its own CI/CD pipeline, monitoring, and deployment schedule\n2. **Distributed system debugging** - Tracing a single request across 12 services was a nightmare\n3. **Data consistency** - Eventual consistency caused more problems than it solved\n4. **Team velocity** - Developers spent more time on infrastructure than features\n\nThe modular monolith gives us clear boundaries, simpler deployments, and faster development. Sometimes the boring technology is the right choice.',
    type: 'text',
    media: [],
    flair: 'Discussion',
    flairColor: 'orange',
    score: 4521,
    userVote: 1,
    commentsCount: 567,
    repostsCount: 892,
    isReposted: false,
    createdAt: '2026-09-28T18:00:00Z',
    isSaved: true,
    isHidden: false,
    isSpoiler: false,
    isNSFW: false,
    isPinned: true,
    isLocked: false,
  },
  {
    id: 'p5',
    communityId: 'c5',
    communityName: 'Music',
    communitySlug: 'music',
    communityIcon: 'https://api.dicebear.com/7.x/shapes/svg?seed=music',
    authorId: 'u5',
    authorName: 'marcusjohnson',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=marcus',
    title: 'What\'s your favorite album of 2026 so far?',
    body: 'We\'re almost at the end of 2026 and it\'s been an incredible year for music. From groundbreaking AI-assisted compositions to a resurgence of analog recording techniques.\n\nMy top 3 so far:\n1. **Radiohead** - "Silent Echoes" - Their most experimental work since Kid A\n2. **Kendrick Lamar** - "DAMN. 2" - A worthy sequel to a classic\n3. **Björk** - "Fossora" - Beautiful, strange, and utterly unique\n\nWhat are your picks?',
    type: 'text',
    media: [],
    flair: 'Discussion',
    flairColor: 'orange',
    score: 1203,
    userVote: 0,
    commentsCount: 234,
    repostsCount: 67,
    isReposted: false,
    createdAt: '2026-09-28T14:30:00Z',
    isSaved: false,
    isHidden: false,
    isSpoiler: false,
    isNSFW: false,
    isPinned: false,
    isLocked: false,
  },
  {
    id: 'p6',
    communityId: 'c1',
    communityName: 'Technology',
    communitySlug: 'technology',
    communityIcon: 'https://api.dicebear.com/7.x/shapes/svg?seed=tech',
    authorId: 'u4',
    authorName: 'emilyzhang',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=emily',
    title: 'Poll: What\'s your primary development language in 2026?',
    body: 'Curious to see what the community is using these days. I\'ve been primarily working in Rust for systems programming and TypeScript for web development.',
    type: 'poll',
    media: [],
    poll: {
      id: 'poll1',
      question: 'What\'s your primary development language in 2026?',
      options: [
        { id: 'o1', text: 'TypeScript/JavaScript', votes: 4521 },
        { id: 'o2', text: 'Python', votes: 3890 },
        { id: 'o3', text: 'Rust', votes: 2103 },
        { id: 'o4', text: 'Go', votes: 1876 },
        { id: 'o5', text: 'Java', votes: 1654 },
        { id: 'o6', text: 'C#', votes: 1432 },
        { id: 'o7', text: 'Other', votes: 987 },
      ],
      totalVotes: 16463,
      endsAt: '2026-10-05T00:00:00Z',
    },
    flair: 'Poll',
    flairColor: 'red',
    score: 3421,
    userVote: 0,
    commentsCount: 892,
    repostsCount: 445,
    isReposted: false,
    createdAt: '2026-09-27T10:00:00Z',
    isSaved: false,
    isHidden: false,
    isSpoiler: false,
    isNSFW: false,
    isPinned: false,
    isLocked: false,
  },
  {
    id: 'p7',
    communityId: 'c6',
    communityName: 'Design',
    communitySlug: 'design',
    communityIcon: 'https://api.dicebear.com/7.x/shapes/svg?seed=design',
    authorId: 'u6',
    authorName: 'oliviawong',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=olivia',
    authorRole: 'moderator',
    title: 'I redesigned the PAxMEDIA landing page - feedback welcome!',
    body: 'Spent the weekend working on a concept redesign of the PAxMEDIA landing page. Focused on improving the visual hierarchy and making the value proposition clearer.\n\nKey changes:\n- Simplified hero section with stronger CTA\n- Added social proof section\n- Improved mobile navigation\n- Better use of whitespace\n\nWould love to hear your thoughts!',
    type: 'image',
    media: [
      {
        id: 'm3',
        type: 'image',
        url: 'https://picsum.photos/seed/designredesign/1200/800',
        width: 1200,
        height: 800,
      },
    ],
    flair: 'Showcase',
    flairColor: 'teal',
    score: 1567,
    userVote: 1,
    commentsCount: 78,
    repostsCount: 123,
    isReposted: false,
    createdAt: '2026-09-27T08:00:00Z',
    isSaved: false,
    isHidden: false,
    isSpoiler: false,
    isNSFW: false,
    isPinned: false,
    isLocked: false,
  },
  {
    id: 'p8',
    communityId: 'c4',
    communityName: 'Science',
    communitySlug: 'science',
    communityIcon: 'https://api.dicebear.com/7.x/shapes/svg?seed=science',
    authorId: 'u4',
    authorName: 'emilyzhang',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=emily',
    title: 'New study reveals breakthrough in quantum error correction',
    body: 'Researchers at MIT have demonstrated a new quantum error correction method that reduces error rates by 90% compared to existing approaches. The technique uses a novel topological approach to protect quantum information.\n\nThis could be the breakthrough that makes practical quantum computing viable within the next decade.',
    type: 'link',
    media: [],
    link: 'https://nature.com/articles/quantum-error-correction-2026',
    flair: 'Research',
    flairColor: 'blue',
    score: 5672,
    userVote: 1,
    commentsCount: 234,
    repostsCount: 567,
    isReposted: false,
    createdAt: '2026-09-26T16:00:00Z',
    isSaved: false,
    isHidden: false,
    isSpoiler: false,
    isNSFW: false,
    isPinned: false,
    isLocked: false,
  },
  {
    id: 'p9',
    communityId: 'c2',
    communityName: 'Gaming',
    communitySlug: 'gaming',
    communityIcon: 'https://api.dicebear.com/7.x/shapes/svg?seed=gaming',
    authorId: 'u3',
    authorName: 'jordanlee',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jordan',
    title: 'The evolution of video game graphics - a visual journey',
    body: 'Created a video showcasing 30 years of video game graphics evolution. From pixel art to photorealistic ray tracing.\n\n[Watch the video](https://youtube.com/watch?v=example)',
    type: 'video',
    media: [
      {
        id: 'm4',
        type: 'video',
        url: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
        thumbnail: 'https://picsum.photos/seed/gamingevolution/800/450',
        width: 800,
        height: 450,
      },
    ],
    flair: 'Video',
    flairColor: 'red',
    score: 3210,
    userVote: 0,
    commentsCount: 445,
    repostsCount: 234,
    isReposted: false,
    createdAt: '2026-09-26T12:00:00Z',
    isSaved: false,
    isHidden: false,
    isSpoiler: false,
    isNSFW: false,
    isPinned: false,
    isLocked: false,
  },
  {
    id: 'p10',
    communityId: 'c7',
    communityName: 'Movies',
    communitySlug: 'movies',
    communityIcon: 'https://api.dicebear.com/7.x/shapes/svg?seed=movies',
    authorId: 'u8',
    authorName: 'lisapark',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=lisa',
    title: 'Dune: Part Three - Official Trailer Breakdown',
    body: 'The trailer for Dune: Part Three just dropped and there\'s so much to unpack. Let\'s break down the key moments and what they might mean for the story.\n\n**Warning: Spoilers for Dune: Part Two ahead**',
    type: 'text',
    media: [
      {
        id: 'm5',
        type: 'image',
        url: 'https://picsum.photos/seed/dunetrailer/1200/675',
        width: 1200,
        height: 675,
      },
    ],
    flair: 'Trailer',
    flairColor: 'yellow',
    score: 2890,
    userVote: 1,
    commentsCount: 312,
    repostsCount: 189,
    isReposted: false,
    createdAt: '2026-09-25T20:00:00Z',
    isSaved: false,
    isHidden: false,
    isSpoiler: true,
    isNSFW: false,
    isPinned: false,
    isLocked: false,
  },
  {
    id: 'p11',
    communityId: 'c8',
    communityName: 'Programming',
    communitySlug: 'programming',
    communityIcon: 'https://api.dicebear.com/7.x/shapes/svg?seed=code',
    authorId: 'u1',
    authorName: 'alexchen',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alex',
    authorRole: 'admin',
    title: 'Show PAxMEDIA: I built a real-time collaborative code editor',
    body: 'Hey everyone! I\'ve been working on a real-time collaborative code editor for the past 6 months and finally launched it.\n\nFeatures:\n- Real-time collaboration with CRDTs\n- Syntax highlighting for 50+ languages\n- Integrated terminal\n- AI-powered code suggestions\n- VS Code extension\n\nBuilt with Rust, WebSockets, and React. Would love to get your feedback!',
    type: 'text',
    media: [
      {
        id: 'm6',
        type: 'image',
        url: 'https://picsum.photos/seed/codeeditor/1200/800',
        width: 1200,
        height: 800,
      },
    ],
    flair: 'Showcase',
    flairColor: 'teal',
    score: 4102,
    userVote: 1,
    commentsCount: 267,
    repostsCount: 345,
    isReposted: false,
    createdAt: '2026-09-25T14:00:00Z',
    isSaved: true,
    isHidden: false,
    isSpoiler: false,
    isNSFW: false,
    isPinned: false,
    isLocked: false,
  },
  {
    id: 'p12',
    communityId: 'c3',
    communityName: 'Photography',
    communitySlug: 'photography',
    communityIcon: 'https://api.dicebear.com/7.x/shapes/svg?seed=photo',
    authorId: 'u2',
    authorName: 'sarahmiller',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarah',
    authorRole: 'moderator',
    title: 'Street photography tips for beginners - a comprehensive guide',
    body: 'After 5 years of street photography, here are my top tips for beginners:\n\n1. **Start with a prime lens** - 35mm or 50mm forces you to move and compose better\n2. **Learn to see light** - The best street photos have interesting light\n3. **Be patient** - Wait for the moment, don\'t chase it\n4. **Shoot in aperture priority** - f/8 is a great starting point\n5. **Edit minimally** - Street photography is about capturing reality\n\nHappy to answer any questions!',
    type: 'gallery',
    media: [
      {
        id: 'm7',
        type: 'image',
        url: 'https://picsum.photos/seed/street1/800/600',
        width: 800,
        height: 600,
      },
      {
        id: 'm8',
        type: 'image',
        url: 'https://picsum.photos/seed/street2/800/600',
        width: 800,
        height: 600,
      },
      {
        id: 'm9',
        type: 'image',
        url: 'https://picsum.photos/seed/street3/800/600',
        width: 800,
        height: 600,
      },
    ],
    flair: 'Guide',
    flairColor: 'green',
    score: 1890,
    userVote: 1,
    commentsCount: 134,
    repostsCount: 78,
    isReposted: false,
    createdAt: '2026-09-24T10:00:00Z',
    isSaved: false,
    isHidden: false,
    isSpoiler: false,
    isNSFW: false,
    isPinned: false,
    isLocked: false,
  },
];

// ─── Comments ───────────────────────────────────────────────────────────────
export const mockComments: Comment[] = [
  {
    id: 'cm1',
    postId: 'p1',
    parentId: null,
    authorId: 'u3',
    authorName: 'jordanlee',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jordan',
    body: 'The Neural Engine improvements are impressive, but I\'m more interested in how they\'re handling the AI privacy concerns. On-device processing is the right approach.',
    score: 234,
    userVote: 1,
    createdAt: '2026-09-29T09:00:00Z',
    isEdited: false,
    isCollapsed: false,
    depth: 0,
    replies: [
      {
        id: 'cm2',
        postId: 'p1',
        parentId: 'cm1',
        authorId: 'u1',
        authorName: 'alexchen',
        authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alex',
        authorRole: 'admin',
        body: 'Absolutely! Apple has been very clear about keeping AI processing on-device whenever possible. The M4\'s Neural Engine is designed specifically for this.',
        score: 156,
        userVote: 1,
        createdAt: '2026-09-29T09:30:00Z',
        isEdited: false,
        isCollapsed: false,
        depth: 1,
        replies: [
          {
            id: 'cm3',
            postId: 'p1',
            parentId: 'cm2',
            authorId: 'u4',
            authorName: 'emilyzhang',
            authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=emily',
            body: 'This is great to hear. Privacy-focused AI is the way forward. Google and Microsoft should take notes.',
            score: 89,
            userVote: 0,
            createdAt: '2026-09-29T10:00:00Z',
            isEdited: false,
            isCollapsed: false,
            depth: 2,
            replies: [],
          },
        ],
      },
      {
        id: 'cm4',
        postId: 'p1',
        parentId: 'cm1',
        authorId: 'u7',
        authorName: 'davidkim',
        authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=david',
        body: 'I\'m skeptical about the "on-device" claims. We\'ll need to see independent verification.',
        score: 45,
        userVote: -1,
        createdAt: '2026-09-29T10:15:00Z',
        isEdited: false,
        isCollapsed: false,
        depth: 1,
        replies: [],
      },
    ],
  },
  {
    id: 'cm5',
    postId: 'p1',
    parentId: null,
    authorId: 'u5',
    authorName: 'marcusjohnson',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=marcus',
    body: 'Does anyone know if the M4 will be compatible with existing Thunderbolt peripherals?',
    score: 67,
    userVote: 0,
    createdAt: '2026-09-29T11:00:00Z',
    isEdited: false,
    isCollapsed: false,
    depth: 0,
    replies: [
      {
        id: 'cm6',
        postId: 'p1',
        parentId: 'cm5',
        authorId: 'u1',
        authorName: 'alexchen',
        authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alex',
        authorRole: 'admin',
        body: 'Yes, it maintains Thunderbolt 4/USB4 compatibility. You won\'t need new peripherals.',
        score: 123,
        userVote: 1,
        createdAt: '2026-09-29T11:30:00Z',
        isEdited: false,
        isCollapsed: false,
        depth: 1,
        replies: [],
      },
    ],
  },
  {
    id: 'cm7',
    postId: 'p4',
    parentId: null,
    authorId: 'u2',
    authorName: 'sarahmiller',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarah',
    body: 'This resonates with our experience. We went through the same journey and found that the operational overhead of microservices was killing our small team\'s productivity.',
    score: 456,
    userVote: 1,
    createdAt: '2026-09-28T19:00:00Z',
    isEdited: false,
    isCollapsed: false,
    depth: 0,
    replies: [
      {
        id: 'cm8',
        postId: 'p4',
        parentId: 'cm7',
        authorId: 'u7',
        authorName: 'davidkim',
        authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=david',
        body: 'Exactly! The key insight is that microservices solve organizational problems, not technical ones. If your team is small, a monolith is almost always the right choice.',
        score: 234,
        userVote: 1,
        createdAt: '2026-09-28T19:30:00Z',
        isEdited: false,
        isCollapsed: false,
        depth: 1,
        replies: [],
      },
    ],
  },
  {
    id: 'cm9',
    postId: 'p4',
    parentId: null,
    authorId: 'u6',
    authorName: 'oliviawong',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=olivia',
    body: 'Counterpoint: Microservices aren\'t just about scale - they\'re about team autonomy. At our company, each team owns their service end-to-end, which dramatically improved ownership and accountability.',
    score: 189,
    userVote: 0,
    createdAt: '2026-09-28T20:00:00Z',
    isEdited: false,
    isCollapsed: false,
    depth: 0,
    replies: [
      {
        id: 'cm10',
        postId: 'p4',
        parentId: 'cm9',
        authorId: 'u7',
        authorName: 'davidkim',
        authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=david',
        body: 'That\'s a fair point. The key is whether your organization actually needs that level of autonomy. For most companies, it\'s premature optimization.',
        score: 145,
        userVote: 1,
        createdAt: '2026-09-28T20:30:00Z',
        isEdited: false,
        isCollapsed: false,
        depth: 1,
        replies: [],
      },
    ],
  },
];

// ─── Notifications ──────────────────────────────────────────────────────────
export const mockNotifications: Notification[] = [
  {
    id: 'n1',
    type: 'comment_reply',
    actorId: 'u3',
    actorName: 'jordanlee',
    actorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jordan',
    message: 'replied to your comment in "Apple announces M4 chip"',
    postId: 'p1',
    commentId: 'cm1',
    isRead: false,
    createdAt: '2026-09-29T09:00:00Z',
  },
  {
    id: 'n2',
    type: 'upvote',
    actorId: 'u2',
    actorName: 'sarahmiller',
    actorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarah',
    message: 'upvoted your post "Show PAxMEDIA: I built a real-time collaborative code editor"',
    postId: 'p11',
    isRead: false,
    createdAt: '2026-09-29T08:00:00Z',
  },
  {
    id: 'n3',
    type: 'follower',
    actorId: 'u4',
    actorName: 'emilyzhang',
    actorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=emily',
    message: 'started following you',
    isRead: false,
    createdAt: '2026-09-28T22:00:00Z',
  },
  {
    id: 'n4',
    type: 'mention',
    actorId: 'u7',
    actorName: 'davidkim',
    actorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=david',
    message: 'mentioned you in "Why I switched from microservices back to a monolith"',
    postId: 'p4',
    isRead: true,
    createdAt: '2026-09-28T18:30:00Z',
  },
  {
    id: 'n5',
    type: 'community',
    actorId: 'u1',
    actorName: 'alexchen',
    actorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alex',
    message: 'Your post was featured in Technology',
    postId: 'p1',
    communityId: 'c1',
    isRead: true,
    createdAt: '2026-09-28T15:00:00Z',
  },
  {
    id: 'n6',
    type: 'message',
    actorId: 'u5',
    actorName: 'marcusjohnson',
    actorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=marcus',
    message: 'sent you a message',
    isRead: true,
    createdAt: '2026-09-27T12:00:00Z',
  },
];

// ─── Conversations ──────────────────────────────────────────────────────────
export const mockConversations: Conversation[] = [
  {
    id: 'conv1',
    participants: [mockUsers[0], mockUsers[1]],
    lastMessage: {
      id: 'msg1',
      conversationId: 'conv1',
      senderId: 'u2',
      senderName: 'sarahmiller',
      senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarah',
      body: 'Hey! Did you see the new M4 announcement?',
      attachments: [],
      isRead: false,
      createdAt: '2026-09-29T10:00:00Z',
    },
    unreadCount: 2,
    isGroup: false,
    updatedAt: '2026-09-29T10:00:00Z',
  },
  {
    id: 'conv2',
    participants: [mockUsers[0], mockUsers[2]],
    lastMessage: {
      id: 'msg2',
      conversationId: 'conv2',
      senderId: 'u1',
      senderName: 'alexchen',
      senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alex',
      body: 'Sure, let me check it out!',
      attachments: [],
      isRead: true,
      createdAt: '2026-09-28T15:00:00Z',
    },
    unreadCount: 0,
    isGroup: false,
    updatedAt: '2026-09-28T15:00:00Z',
  },
  {
    id: 'conv3',
    participants: [mockUsers[0], mockUsers[3], mockUsers[4]],
    lastMessage: {
      id: 'msg3',
      conversationId: 'conv3',
      senderId: 'u4',
      senderName: 'emilyzhang',
      senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=emily',
      body: 'The project looks great! Nice work everyone.',
      attachments: [],
      isRead: false,
      createdAt: '2026-09-28T12:00:00Z',
    },
    unreadCount: 1,
    isGroup: true,
    groupName: 'Project Team',
    updatedAt: '2026-09-28T12:00:00Z',
  },
];

// ─── Messages ───────────────────────────────────────────────────────────────
export const mockMessages: Message[] = [
  {
    id: 'msg1',
    conversationId: 'conv1',
    senderId: 'u2',
    senderName: 'sarahmiller',
    senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarah',
    body: 'Hey! Did you see the new M4 announcement?',
    attachments: [],
    isRead: false,
    createdAt: '2026-09-29T10:00:00Z',
  },
  {
    id: 'msg2',
    conversationId: 'conv1',
    senderId: 'u1',
    senderName: 'alexchen',
    senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alex',
    body: 'Yes! The Neural Engine improvements are incredible. 38 TOPS is no joke.',
    attachments: [],
    isRead: true,
    createdAt: '2026-09-29T10:05:00Z',
  },
  {
    id: 'msg3',
    conversationId: 'conv1',
    senderId: 'u2',
    senderName: 'sarahmiller',
    senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarah',
    body: 'Right? I\'m thinking about upgrading my MacBook Pro now.',
    attachments: [],
    isRead: false,
    createdAt: '2026-09-29T10:10:00Z',
  },
];

// ─── Reports ────────────────────────────────────────────────────────────────
export const mockReports: Report[] = [
  {
    id: 'rep1',
    type: 'post',
    targetId: 'p1',
    targetTitle: 'Apple announces M4 chip with revolutionary AI capabilities',
    reporterId: 'u3',
    reporterName: 'jordanlee',
    reason: 'Misinformation',
    status: 'pending',
    createdAt: '2026-09-29T08:00:00Z',
  },
  {
    id: 'rep2',
    type: 'comment',
    targetId: 'cm1',
    targetTitle: 'The Neural Engine improvements are impressive...',
    reporterId: 'u4',
    reporterName: 'emilyzhang',
    reason: 'Harassment',
    status: 'pending',
    createdAt: '2026-09-29T07:00:00Z',
  },
  {
    id: 'rep3',
    type: 'user',
    targetId: 'u5',
    targetTitle: 'marcusjohnson',
    reporterId: 'u6',
    reporterName: 'oliviawong',
    reason: 'Spam',
    status: 'approved',
    moderatorId: 'u1',
    createdAt: '2026-09-28T20:00:00Z',
    resolvedAt: '2026-09-28T21:00:00Z',
  },
];

// ─── Bans ───────────────────────────────────────────────────────────────────
export const mockBans: Ban[] = [
  {
    id: 'ban1',
    userId: 'u5',
    username: 'marcusjohnson',
    reason: 'Repeated spam violations',
    moderatorId: 'u1',
    moderatorName: 'alexchen',
    communityId: 'c5',
    communityName: 'Music',
    isPermanent: false,
    expiresAt: '2026-10-28T00:00:00Z',
    createdAt: '2026-09-28T21:00:00Z',
  },
];
