; Local development overrides
; This file is mounted in development mode

display_errors = On
display_startup_errors = On
error_reporting = E_ALL

; Disable OPcache in development
opcache.enable=0
opcache.enable_cli=0
